### ISSUE TITLE
Are there Pre trained Weights Availabe?

### ISSUE THREAD

**Issue by paukiss** [rekon/Smoke-semantic-segmentation#2]
I was wondering if the correct pre trained weights could be obtained from somewhere, because the weights provided with the repo are not correspondent to the U-Net model, neither Link-Net.

**Comment by rekon** [comment]
As far as I remember, I have not provided any links to pretrained weights, nor do I intend to. I have also done some modifications according to my use-case, however original sources are provided in Readme, please refer them if necessary
