### ISSUE TITLE
"Inaccurate" predictions

### ISSUE THREAD

**Issue by vid1988** [rekon/Smoke-semantic-segmentation#3]
Hi,

I've tried to train the net (notebook) with provided examples / preferences, so as it is. 
I do not get nearly the same accuracy than provided in your example image. Did you train the network for those example figures with other model / training-parameters?
Same linknet <-> unet (unet provides at least some bounding box around smoke, linket basically classifies complete image to be smoke)

The accuracy you provide with the example images would be highly sufficient. Computing resources would be available. 

cheers
David

**Comment by rekon** [comment]
> Did you train the network for those example figures with other model / training-parameters?

No, these are the only two models that I used. I had tuned the hyper-parameters, but those again depend on your computing resources, sample set etc. But one point worth mentioning, if you want more of image augmentation, you can use this library - [imgaug](https://imgaug.readthedocs.io/en/latest/)
